@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods


class ProductManager{

}

class Subscription{
    -id
    -subType
    -date
    -subState
    -feeType
    -cancellations
    -subscriptions
}


ProductManager "1" -> "1..*" Subscription: analyze


@enduml