@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Admin" as User
participant ":PlanBoostrapper" as Ctrl
participant "PlanRepo:PlanRepository" as Repo

activate User

User -> Ctrl: asks to bootstrap user credential data
loop for each credential
    Ctrl -> Repo: checks if the credentials already exist
    Repo --> Ctrl: if not, creates plan with the appropriate role and saves it
end loop

@enduml