@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Marketing director" as Person
participant ":System" as System

activate Person

Person -> System:PUT(/api/plan/deactivate/{planType})

System --> Person: 200:OK

@enduml