@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title migrate all subscribers

class Subscription{
    -id
    -subType
    -date
    -subState
    -feeType
    -cancellations
    -subscriptions
}

class MarktingDirector{
    -username
    -fullName
    -password
    -rePassword
    -authorities
}

MarktingDirector "1" -right--> "1..*" Subscription: Migrates to other plan

@enduml